### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by ktcshust** [MicrosoftDocs/power-pages-docs#1]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f644196a-53da-3f06-dd3e-33a49d0b218b
* Version Independent ID: f644196a-53da-3f06-dd3e-33a49d0b218b
* Content: [Sign up for a free trial - Power Pages](https://docs.microsoft.com/en-us/power-pages/getting-started/trial-signup)
* Content Source: [power-pages-docs/getting-started/trial-signup.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/trial-signup.md)
* Service: **power-pages**
* GitHub Login: @sampatn
* Microsoft Alias: **sampatn**

**Comment by nickdoelman** [comment]
Thank you!
