### ISSUE TITLE
Portal Table Permissions & Many-to-Many relationships undocumented?

### ISSUE THREAD

**Issue by dtsoden** [MicrosoftDocs/power-pages-docs#10]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5dd7334-1124-4cb2-322a-79a6735d5852
* Version Independent ID: e5dd7334-1124-4cb2-322a-79a6735d5852
* Content: [Configuring table permissions in Power Pages](https://learn.microsoft.com/en-us/power-pages/security/table-permissions)
* Content Source: [power-pages-docs/security/table-permissions.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/table-permissions.md)
* Service: **power-pages**
* GitHub Login: @nickdoelman
* Microsoft Alias: **ndoelman**

**Comment by nickdoelman** [comment]
Thank you for your feedback. Are you trying to configure child permissions using a many-to-many relationship? This is a supported scenario. Make sure that you have selected and run the *sync* button on the design studio and that all table configurations have been published. If this continues to be an issue, please open a support ticket through https://admin.powerplatform.microsoft.com/support
