### ISSUE TITLE
Logo not showing when preview

### ISSUE THREAD

**Issue by Joy-Projects** [MicrosoftDocs/power-pages-docs#106]
[Enter feedback here]

Case 1: 
I have developed a website from scratch, I have added a logo and design and header and given backgrounds but when i click on preview it is not showing my company name and brand logo. 

Case 2: 
If i take a template and upload and logo and given a brand name and design a header and other parts. It is showing correctly.

But when comes to new blank template it is not working. 

Can any one help me on this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14ffe441-823a-de9f-c7d0-107ade4b2a47
* Version Independent ID: 14ffe441-823a-de9f-c7d0-107ade4b2a47
* Content: [Tutorial: Style your site](https://learn.microsoft.com/en-us/power-pages/getting-started/tutorial-style-site)
* Content Source: [power-pages-docs/getting-started/tutorial-style-site.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/tutorial-style-site.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @clromano
* Microsoft Alias: **clromano**

**Comment by ProfessorKendrick** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: [https://powerpages.microsoft.com/en-us/support/](https://admin.powerplatform.microsoft.com/support%22%20HYPERLINK%20%22https://powerpages.microsoft.com/en-us/support/) 

Closing this issue.
