### ISSUE TITLE
Should Azure references be changed to Entra?

### ISSUE THREAD

**Issue by barbj** [MicrosoftDocs/power-pages-docs#108]
Shouldn't the references to _Azure_ on this page be _Entra ID_ and the steps in "_Create an app registration in Azure_" be updated accordingly?  Especially since the index entry is _Entra ID_:

![image](https://github.com/MicrosoftDocs/power-pages-docs/assets/24277731/a3053e9d-bbec-4005-989b-9c2bdc01e897)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77f17d72-6a7f-fe56-40da-3c6066b8b4b7
* Version Independent ID: 77f17d72-6a7f-fe56-40da-3c6066b8b4b7
* Content: [Set up an OpenID Connect provider with Microsoft Entra ID](https://learn.microsoft.com/en-us/power-pages/security/authentication/openid-settings)
* Content Source: [power-pages-docs/security/authentication/openid-settings.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/authentication/openid-settings.md)
* Service: **power-pages**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Our team is working to update documentation related to the name change and this will be fixed soon.  Closing the issue.
