### ISSUE TITLE
Following this doc only seems to creat a liquid tag without path that fails to open a PowerBI report 

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/power-pages-docs#14]
please add a link on this page to

https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/add-powerbi-report
which shows the liquid tag with path setting that needs to be set, with an example of

{% powerbi authentication_type:"powerbiembedded" path:"https://app.powerbi.com/groups/00000000-0000-0000-0000-000000000000/reports/00000000-0000-0000-0000-000000000001/ReportSection01" %}

not following this results in
Liquid syntax error: Syntax Error in ‘powerbi’ tag. Missing required attribute ‘path:[string]’

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  This topic applies to legacy capabilities. For latest information, go to Microsoft Power Pages documentation: https://learn.microsoft.com/en-us/power-pages/getting-started/add-power-bi. Closing the issue.
