### ISSUE TITLE
A sentence might need adjusting but I am unsure.

### ISSUE THREAD

**Issue by AJ-Zafar** [MicrosoftDocs/power-pages-docs#22]
[When reading this page I found it quite helpful, however, I was unsure on this section:

"Requirements for the SSL Certificate that will be required in order to set up your custom domain. For more information, see [Custom Domains](https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/add-custom-domain) in the Power Apps portals documentation."

Does the first sentence mean to say:
SSL Certificates are required in order to set up your custom domain. 

I may simply be reading this wrong so I didn't do the edit myself and instead thought to raise it as an issue.
Link to page:
https://learn.microsoft.com/en-us/power-pages/configure/planning-power-pages-project]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3488bda-6b40-b98e-993d-becf029a5667
* Version Independent ID: b3488bda-6b40-b98e-993d-becf029a5667
* Content: [Plan your Power Pages project](https://learn.microsoft.com/en-us/power-pages/configure/planning-power-pages-project)
* Content Source: [power-pages-docs/configure/planning-power-pages-project.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/planning-power-pages-project.md)
* Service: **power-pages**
* GitHub Login: @NikitaPolyakovMSFT
* Microsoft Alias: **ndoelman**

**Comment by ProfessorKendrick** [comment]
Thank you for the suggested edit.

Closing this issue.
