### ISSUE TITLE
Desperate Plea - Impossible for retired with no work email to pay for Power Pages

### ISSUE THREAD

**Issue by Rightron** [MicrosoftDocs/power-pages-docs#24]
Title says it all - no escape or advancing if one doesn't work

Ron Hufham
rightron@roadrunner.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca26628a-a16f-a110-9276-d4896c311558
* Version Independent ID: ca26628a-a16f-a110-9276-d4896c311558
* Content: [Preview features in trial - Power Pages](https://learn.microsoft.com/en-us/power-pages/getting-started/preview-features-trial?WT.mc_id=powerportals_marketing_header)
* Content Source: [power-pages-docs/getting-started/preview-features-trial.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/preview-features-trial.md)
* Service: **power-pages**
* GitHub Login: @nickdoelman
* Microsoft Alias: **tbhagwat**

**Comment by nickdoelman** [comment]
Thank you for reaching out and your feedback. Power Pages uses [Power Platform environments](https://learn.microsoft.com/power-platform/admin/environments-overview) that are created under Azure AD tenant. If you don’t have an active Azure AD tenant, you can sign up to try [free for one month](https://www.microsoft.com/microsoft-365/business/compare-all-microsoft-365-business-products?rtc=1). And then, sign up for a [Power Pages trial](https://learn.microsoft.com/power-pages/getting-started/trial-signup).
Another option is to consider is the [Microsoft 365 Developer Program](https://developer.microsoft.com/microsoft-365/dev-program).
