### ISSUE TITLE
CDN Links 

### ISSUE THREAD

**Issue by Squire4Hire** [MicrosoftDocs/power-pages-docs#25]
Custom styles are more than just updating base theme configurations and uploading CSS files manually. Please provide an example and explanation of where/how to implement link tags in the site head with CDN references to css packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54ed47c3-0422-b051-b7e8-fb8c87dbbeeb
* Version Independent ID: 54ed47c3-0422-b051-b7e8-fb8c87dbbeeb
* Content: [Tutorial: Add custom CSS to your site](https://learn.microsoft.com/en-us/power-pages/getting-started/tutorial-add-custom-style)
* Content Source: [power-pages-docs/getting-started/tutorial-add-custom-style.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/tutorial-add-custom-style.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @ankitavish
* Microsoft Alias: **avishwakarma**

**Comment by nickdoelman** [comment]
Thank you for the feedback, we will take this suggestion under advisement as we expand our guidance section.
