### ISSUE TITLE
Link to FetchXML is dead / leads nowhere

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/power-pages-docs#29]
[Enter feedback here]
Please correct

https://learn.microsoft.com/en-us/developer/data-platform/use-fetchxml-construct-query

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 086e493d-26d0-83c1-55cd-62f592ede2ca
* Version Independent ID: 086e493d-26d0-83c1-55cd-62f592ede2ca
* Content: [Overview of the Power Pages portals Web API](https://learn.microsoft.com/en-us/power-pages/configure/web-api-overview#known-issues)
* Content Source: [power-pages-docs/configure/web-api-overview.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/web-api-overview.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by KumarVivek** [comment]
Closing this as the issues does not mention what to fix.
