### ISSUE TITLE
Additional start step

### ISSUE THREAD

**Issue by TinoRabe** [MicrosoftDocs/power-pages-docs#3]
Hi, I like the list of start steps to get new Portal users rolling.
Still, one thing is missing from my view: consider localization (i.e. required language support).
Too often, this is overlooked from the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486c0cce-55fd-2aae-6206-336e61a904bd
* Version Independent ID: 486c0cce-55fd-2aae-6206-336e61a904bd
* Content: [Go live checklist for Power Pages](https://docs.microsoft.com/en-us/power-pages/go-live/checklist)
* Content Source: [power-pages-docs/go-live/checklist.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/go-live/checklist.md)
* Service: **power-pages**
* GitHub Login: @NikitaPolyakovMSFT
* Microsoft Alias: **ndoelman**

**Comment by nickdoelman** [comment]
Thanks for the feedback, we will take this under advisement.
