### ISSUE TITLE
Website spelled wrong and Reset a website links to Deleting a Website

### ISSUE THREAD

**Issue by johnnycchapman** [MicrosoftDocs/power-pages-docs#30]
1) Website is spelled wrong in the description right below the header at this [link](https://learn.microsoft.com/en-us/power-pages/admin/site-checker-startup-issue#website-binding-not-found).

2) Links to **Reset the website** [here](https://learn.microsoft.com/en-us/power-pages/admin/site-checker-startup-issue#an-unexpected-error-has-occurred-while-trying-to-connect-to-your-microsoft-dataverse-environment) link to the **Delete a website** [page](https://learn.microsoft.com/en-us/power-pages/admin/delete-website). Not sure if it was intentional or not, but was something I noticed when referring to these docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aec8093f-b07e-20fb-0dea-5444c99d927d
* Version Independent ID: aec8093f-b07e-20fb-0dea-5444c99d927d
* Content: [Site Checker startup issues](https://learn.microsoft.com/en-us/power-pages/admin/site-checker-startup-issue)
* Content Source: [power-pages-docs/admin/site-checker-startup-issue.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/admin/site-checker-startup-issue.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for your feedback. The spelling error has been resolved. The "reset" functionality has been removed as it essentially did the same thing as the delete website process. The documentation has been updated.
