### ISSUE TITLE
Issue related to  Site setting status

### ISSUE THREAD

**Issue by Pratima810** [MicrosoftDocs/power-pages-docs#33]
[Enter feedback here]

Hi Team,

Information mentioned at URL https://learn.microsoft.com/en-us/power-pages/configure/webapi-how-to is very useful.
I created mentioned site setting and it worked. But when i deactivated these settings then also i was able to get data with Portal URI]/_api/contacts. Ideally it should not consider deactivated site settings.

Thanks,
Pratima Mane
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb07aab-7507-229a-2d2a-c60a9e0029f6
* Version Independent ID: 1bb07aab-7507-229a-2d2a-c60a9e0029f6
* Content: [How to: Use the portal Web API](https://learn.microsoft.com/en-us/power-pages/configure/webapi-how-to)
* Content Source: [power-pages-docs/configure/webapi-how-to.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/webapi-how-to.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We tested the functionality and it works on our end, did you [clear the cache](https://learn.microsoft.com/power-pages/admin/clear-server-side-cache) after deactivating the site settings? If this continues to be an issue, please let us know.
