### ISSUE TITLE
Does not answer the question we were sent here for!

### ISSUE THREAD

**Issue by adamkempler** [MicrosoftDocs/power-pages-docs#37]
For example, signing up for a service with my email address gives an error:
Let's get started
Enter your email to start your free trial.

<akempler@gmail.com>
Please enter a work account for the best trial experience.
**To continue with "akempler@gmail.com", please follow these [steps](https://go.microsoft.com/fwlink/?LinkId=2195529&clcid=0x409) .**

So I follow that link here and there is nothing there about using that email address. 
What the hell?

Please provide information on how to use your own email address.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1720a9fd-f9a5-4eec-ec69-642e69b2556f
* Version Independent ID: 1720a9fd-f9a5-4eec-ec69-642e69b2556f
* Content: [Trial FAQ - Power Pages](https://learn.microsoft.com/en-us/power-pages/getting-started/trial-faq#what-email-address-can-i-use)
* Content Source: [power-pages-docs/getting-started/trial-faq.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/trial-faq.md)
* Service: **power-pages**
* GitHub Login: @sampatn
* Microsoft Alias: **sampatn**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the documentation to clarify the requirement to use a work or school email account connected to Microsoft 365. You can sign up for Microsoft 365 or Dynamics 365 trial using your personal email address, which in turn will provide you with a work or school email address to try Power Pages.
