### ISSUE TITLE
Information mismatch on steps to configure Power Pages + Azure B2C Provider

### ISSUE THREAD

**Issue by chris-nguyen-MSFT** [MicrosoftDocs/power-pages-docs#38]
***There are no production urls/guids in this issue item***

### Getting/setting the iss claim URL
Step 7a iv states: 

```
Ensure that you copy only the URL, without the quotation marks ("").
For example, https://contosoorg.b2clogin.com/tfp/799f7b50-f7b9-49ec-ba78-67eb67210998/b2c_1_contoso/v2.0/
``` 
The tip box below calls out to use the issuer with tfp in the claims URL; screenshot below: 

<img width="429" alt="image" src="https://github.com/MicrosoftDocs/power-pages-docs/assets/93615906/c19e90ca-9357-43ef-aed4-eda3a95445f5">

### Creating the iss claim URL
Step 6d earlier in the page outlines how to [Create user flows and custom policies in Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow#create-a-sign-up-and-sign-in-user-flow). There are no explicit steps to update token compatibility settings to use the iss claims url (with tfp) as outlined above: 

<img width="533" alt="image" src="https://github.com/MicrosoftDocs/power-pages-docs/assets/93615906/62e1a979-b091-4682-be59-d122f120ce60">

To contrast, the manual configuration calls out this step for tfp: [Configure token compatibility](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens#configure-token-compatibility) by using an Issuer (iss) claim URL that includes tfp. More information: [Token compatibility](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#compatibility)

```Configure token compatibility by using an Issuer (iss) claim URL that includes tfp. More information: Token compatibility```

![image](https://github.com/MicrosoftDocs/power-pages-docs/assets/93615906/8c4dc23b-a285-488a-a8b2-8b95c186f699)

### Additional
Completing steps 7b - Valid Issuers also then refers to the non-tfp iss claims URL as above. 

Also within step 7b - Valid issuers: A discrepancy in the following: ```To get the issuer URLs for the sign-up and sign-in user flow, and the password reset user flow, open each flow and then follow the steps under Authority, in step 5a earlier in this article.``` 

Step 5a says: ```Select Next for the next set of steps.```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fd6db56-99a5-88f1-e480-334855818e83
* Version Independent ID: 2fd6db56-99a5-88f1-e480-334855818e83
* Content: [Configure the Azure Active Directory B2C provider](https://learn.microsoft.com/en-us/power-pages/security/authentication/azure-ad-b2c-provider)
* Content Source: [power-pages-docs/security/authentication/azure-ad-b2c-provider.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/authentication/azure-ad-b2c-provider.md)
* Service: **power-pages**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by ProfessorKendrick** [comment]
Thank you for working with us to resolve this issue.  Closing the issue.
