### ISSUE TITLE
Documentation differs from what is seen in reality

### ISSUE THREAD

**Issue by FintanGuihen** [MicrosoftDocs/power-pages-docs#39]
Documentation appears out of date. there is no "Site" option in the "add existing" menu in my power pages development portal.
I have posted about it here, including screenshots:
https://powerusers.microsoft.com/t5/General-Discussions/Cannot-add-power-pages-site-to-a-solution/m-p/2176574#M3162

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5f7113-9544-1bd9-aebe-2cd10ff9273b
* Version Independent ID: 6c5f7113-9544-1bd9-aebe-2cd10ff9273b
* Content: [Using solutions with Power Pages](https://learn.microsoft.com/en-us/power-pages/configure/power-pages-solutions)
* Content Source: [power-pages-docs/configure/power-pages-solutions.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/power-pages-solutions.md)
* Service: **power-pages**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback, for the site option to appear, you will need to have a least one website that was created using the enhanced data model. Documentation has been updated.
