### ISSUE TITLE
Plans regarding Bootstrap V3

### ISSUE THREAD

**Issue by MJBoes** [MicrosoftDocs/power-pages-docs#4]
Are there any plans to allow a styling framework of choice a possibility for Power Pages? Or update to v5? Bootstrap V3 is a bit end of live-ish for this new phase in Portals.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ed47c3-0422-b051-b7e8-fb8c87dbbeeb
* Version Independent ID: 54ed47c3-0422-b051-b7e8-fb8c87dbbeeb
* Content: [Tutorial: Add custom CSS to your site](https://docs.microsoft.com/en-gb/power-pages/getting-started/tutorial-add-custom-style)
* Content Source: [power-pages-docs/getting-started/tutorial-add-custom-style.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/tutorial-add-custom-style.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @nickdoelman
* Microsoft Alias: **ndoelman**

**Comment by nickdoelman** [comment]
Thank you for your feedback. The ability to use Bootstrap v5 is currently under review.
