### ISSUE TITLE
This doesn't seem to work for me, no data when using .Name, .Size or .Url

### ISSUE THREAD

**Issue by JStroinski** [MicrosoftDocs/power-pages-docs#41]
Hi, is this meant for some specific version of power pages? I'm using 9.5.4.12 , when trying to display url/name from "item.filecolumn.Url" i'm not getting any data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8126476-4792-8fa3-1854-9a3b1393eefd
* Version Independent ID: c8126476-4792-8fa3-1854-9a3b1393eefd
* Content: [Configure a file column on Power Pages](https://learn.microsoft.com/en-us/power-pages/configure/file-column)
* Content Source: [power-pages-docs/configure/file-column.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/file-column.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @nageshbhat-msft
* Microsoft Alias: **nabha**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We cannot reproduce this issue and this feature should work for portals version 9.5.4.12. The sample code provided does need to be modified to reflect your specific table and field names. If this continues to be an issue, we recommend opening a support ticket.

**Comment by fowl2** [comment]
One thing to check is to ensure that the "main" table in you fetch xml is the one with the file column. If you're doing joins (eg. generated by SQL 4 CDS), sometimes the tables will get flipped around, and then the special properties won't be loaded.
