### ISSUE TITLE
Receive Alerts from Microsoft on website authentication key expiry

### ISSUE THREAD

**Issue by gajulajyothi17** [MicrosoftDocs/power-pages-docs#45]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 387b023a-e9cf-c129-61bd-aed679af581e
* Version Independent ID: 387b023a-e9cf-c129-61bd-aed679af581e
* Content: [Manage website authentication key](https://learn.microsoft.com/en-us/power-pages/admin/manage-auth-key#check-authentication-key-expiration-notification)
* Content Source: [power-pages-docs/admin/manage-auth-key.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/admin/manage-auth-key.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Can you provide some more details?

**Comment by ProfessorKendrick** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
