### ISSUE TITLE
Step 3.2 is absolutely vague - 

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-pages-docs#46]
[Enter feedback here]
Maybe it is repetition of the previous step.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab7c843-301a-0f60-bb52-dbdaad4f18f0
* Version Independent ID: aab7c843-301a-0f60-bb52-dbdaad4f18f0
* Content: [Tutorial: Use dataset code components](https://learn.microsoft.com/en-us/power-pages/configure/tutorial-pcf-code#step-2---add-the-code-component-to-views-or-subgrids-in-a-model-driven-app)
* Content Source: [power-pages-docs/configure/tutorial-pcf-code.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/tutorial-pcf-code.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback and for calling that out. It was a repetition of that step, and that particular documentation issue has been rectified.
