### ISSUE TITLE
How to actually use it?

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-pages-docs#47]
[Enter feedback here]
There is absolutely no guidance on how to actually use the editable Power Apps Editable Grid in Power Pages. Just steps to enable code component.

In the section 'Add dataset-based code component using liquid tag', just vague reference is provided to liquid code. Nothing meaningful/useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aab7c843-301a-0f60-bb52-dbdaad4f18f0
* Version Independent ID: aab7c843-301a-0f60-bb52-dbdaad4f18f0
* Content: [Tutorial: Use dataset code components](https://learn.microsoft.com/en-us/power-pages/configure/tutorial-pcf-code#step-2---add-the-code-component-to-views-or-subgrids-in-a-model-driven-app)
* Content Source: [power-pages-docs/configure/tutorial-pcf-code.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/tutorial-pcf-code.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
There was a bug with the code that is now rolling out.
