### ISSUE TITLE
Clarify header and footer output cache behavior

### ISSUE THREAD

**Issue by richardcarrigan** [MicrosoftDocs/power-pages-docs#48]
It's unclear from this documentation whether or not applying the template source code changes will allow a custom header and/or footer to also be cached, or if that only applies to the `Header` and `Footer` web templates. I would assume that the output would be cached for any web template that is specified as the website's `Header Template` and `Footer Template`, but that assumption seems impossible to validate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91747e3b-2a0b-c046-a88b-e2ffd6b22f61
* Version Independent ID: 91747e3b-2a0b-c046-a88b-e2ffd6b22f61
* Content: [Enable header and footer output caching on Power Pages](https://learn.microsoft.com/en-us/power-pages/configure/enable-header-footer-output-caching)
* Content Source: [power-pages-docs/configure/enable-header-footer-output-caching.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/enable-header-footer-output-caching.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by nickdoelman** [comment]
Output caching can be configured for both the out-of-the-box and custom web templates specified in the Header Template and Footer Template fields in the options section of the website record. Documentation updated and issue closed.
