### ISSUE TITLE
Limitation of the D365 templates

### ISSUE THREAD

**Issue by randolphnz** [MicrosoftDocs/power-pages-docs#49]
Hi there,

For the limitation of the D365 templates, it says "Dynamics 365 templates are not available during the first run experience for site creation." Does it mean the templates won't be available when we create the first power pages site even in an environment which already contains D365 apps?

Regards,
Randy
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19520975-cb97-7c0f-3290-1526925e05d4
* Version Independent ID: 19520975-cb97-7c0f-3290-1526925e05d4
* Content: [Dynamics 365 templates](https://learn.microsoft.com/en-us/power-pages/templates/dynamics-365-apps/overview)
* Content Source: [power-pages-docs/templates/dynamics-365-apps/overview.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/templates/dynamics-365-apps/overview.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @sampatn
* Microsoft Alias: **sampatn**

**Comment by nickdoelman** [comment]
That is correct. The first run experience will only allow you to use the standard Power Pages templates even if Dynamics 365 has been enabled. However, once your first site is created, then you will be able to create additional sites using the Dynamics 365 templates, assuming Dynamics 365 has been enabled.

**Comment by sampatn** [comment]
[like]  Vinay Nalam reacted to your message:
________________________________
