### ISSUE TITLE
How to edit and delete Header and Footer and add hyperlinks to text areas?  

### ISSUE THREAD

**Issue by oshihirii** [MicrosoftDocs/power-pages-docs#5]
Hello,

I have just signed up to test Microsoft Power Pages.  

I am not familiar with Power Apps (which it seems to sit on top of, or be a development of).  

To get started, I just want to create a simple blank page, with two links on it.  

I have started with the Default template.  

I have deleted all the sections.  

When I delete the Header and Footer they just keep re-appearing.  

I cannot delete the Navigation Menu in the Header.  

There seems to be no capability in the text editor to add hyperlinks.  

(I had to go to 'code view' and manually insert the hyperlink HTML markup).  

How can I delete the Header and Footer? 

How can I remove the navigation menu from the Header?  

How can I add hyperlinks to text areas?  

Thank You.  

Edit:  

I am looking at this page:

https://docs.microsoft.com/en-us/power-pages/templates/default-template

But it just links through to this page:

https://docs.microsoft.com/en-us/power-pages/getting-started/use-design-studio

which doesn't provide answers I am seeking.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 118aba47-70d2-cc2a-2675-5a9b1d52e8c9
* Version Independent ID: 118aba47-70d2-cc2a-2675-5a9b1d52e8c9
* Content: [Customize webpages](https://docs.microsoft.com/en-us/power-pages/getting-started/customize-pages)
* Content Source: [power-pages-docs/getting-started/customize-pages.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/customize-pages.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @nickdoelman
* Microsoft Alias: **ndoelman**

**Comment by nickdoelman** [comment]
Thank you for your comment. You cannot remove the header and footer with the Pages workspace. We have added a note to the documentation. 

To achieve this, you will need to create a custom page layout. More information can be found here: [https://docs.microsoft.com/power-apps/maker/portals/liquid/create-custom-template](https://docs.microsoft.com/power-apps/maker/portals/liquid/create-custom-template)


You currently need to add a hyperlink to text using the code editor in the studio. Your feedback has been noted.
