### ISSUE TITLE
Example of how to update a lookup field in portal JS using PUT

### ISSUE THREAD

**Issue by TanerRiffat** [MicrosoftDocs/power-pages-docs#50]
[Enter feedback here]
Example needed of how to update a lookup field in portal JS using PUT.

Seriously guys, do you just not care???????

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ac58d9f-2c88-1d5c-0e8e-86d82d162303
* Version Independent ID: 9ac58d9f-2c88-1d5c-0e8e-86d82d162303
* Content: [Portals Web API write, update, and delete operations](https://learn.microsoft.com/en-us/power-pages/configure/write-update-delete-operations)
* Content Source: [power-pages-docs/configure/write-update-delete-operations.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/write-update-delete-operations.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
The process to add or update a lookup field using the Power Pages WebAPI is determined associating related lookup tables using the @odata.bind as outlined in our [documentation](https://learn.microsoft.com/power-pages/configure/write-update-delete-operations#associate-and-disassociate-tables-by-using-the-web-api).

For example, to update an Account’s primary contact lookup, the code could look something like this:

```
var record = {};
record[[primarycontactid@odata.bind](mailto:primarycontactid@odata.bind)] = "/contacts(e797d473-260a-ee11-8f6d-000d3a8b42b8)"; // Lookup

webapi.safeAjax({
              type: "PATCH",
              contentType: "application/json",
              url: "/_api/accounts(d397d473-260a-ee11-8f6d-000d3a8b42b8)",
              data: JSON.stringify(record),
              success: function (data, textStatus, xhr) {
                             console.log("Record updated");
              },
              error: function (xhr, textStatus, errorThrown) {
                             console.log(xhr);
              }
});
```
