### ISSUE TITLE
Add roles that are required for Power BI Embedded Service administration

### ISSUE THREAD

**Issue by etgh1** [MicrosoftDocs/power-pages-docs#51]
Please add a section listing all of the roles required to administer the Power BI Embedded service for Power Pages to this article. One of our M365 Global Admins (who also has Power Platform Admin role) tried to set up PBI Embedded and keeps getting told he must belong to a specific security role...but the missing role isn't clarified. The full error text (with a link to the referenced article) is:

> You must be a member of the security role(s) allowed to perform this operation. Learn more about the required security roles

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20c84550-bfea-6a51-3b10-87175c8a038b
* Version Independent ID: 20c84550-bfea-6a51-3b10-87175c8a038b
* Content: [Roles required for Power Pages administration](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles)
* Content Source: [power-pages-docs/admin/admin-roles.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/admin/admin-roles.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thanks for the feedback.
I want to clarify that you have seen this topic as well:

https://learn.microsoft.com/power-pages/admin/set-up-power-bi-integration#create-security-group-and-add-to-power-bi-account

If you have followed the steps in that topic (above) and are still having issues, you may have to open a support ticket to help isolate the problem or if there is something specific in your configuration. 

Can you let us know where you specifically see the "learn more" link? In case we need to reconsider the redirection for that link.

Thank you!

**Comment by etgh1** [comment]
Thanks for the reply, @nickdoelman. 

> I want to clarify that you have seen this topic as well:
>https://learn.microsoft.com/power-pages/admin/set-up-power-bi-integration#create-security-group-and-add-to-power-bi-account

Yes. I created the group, added the Portal app reg to it, and added it as an allowed security group in the PBI admin portal under the **Allow service principals to use Power BI APIs** setting as instructed. Our GA also has admin access to the PBI Workspace in question, so there's nothing we can find from the docs that would explain the "You must be a member of a the security role..." error message.

> If you have followed the steps in that topic (above) and are still having issues, you may have to open a support ticket to help isolate the problem or if there is something specific in your configuration.

Regarding support, I have sent up a ticket but it's been about a week and a half with zero reply. I've been hoping it's just that there's a role missing from the doc or something.

> Can you let us know where you specifically see the "learn more" link? In case we need to reconsider the redirection for that link.

The "learn more" link is provided in the "You must be a member of a the security role..." error that appears when our Global Admin clicks on the Edit Workspaces link in the Admin Center (step 3 in [this doc section](https://learn.microsoft.com/en-us/power-pages/admin/set-up-power-bi-integration#enable-power-bi-embedded-service)).

Considering the fact that he's a GA and the [Roles Required](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles) doc states that the role required to administer Power BI integration is Global Admin, both that error and the "unexpected" one are a bit of a headscratcher. I did discover that the Global Admin had to have **Power Platform Admin** role assigned or else he couldn't even view the page at all in the Admin Center.

**Comment by nickdoelman** [comment]
We reviewed the steps and based on our information; you should only require the global admin role + following the steps to create the security group to enable Power BI embedded. 
However, there may be some additional configuration or settings preventing you from enabling Power BI embedded. We encourage you to continue to engage with support as they should be able to help you with isolating the issue.
