### ISSUE TITLE
Use developer websites: How to create?

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/power-pages-docs#53]
Developer sites sound great, but unless I'm missing something this page doesn't actually say how to create them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6da19427-9c92-47b6-a1db-4254a67ce597
* Version Independent ID: 6da19427-9c92-47b6-a1db-4254a67ce597
* Content: [Use developer websites](https://learn.microsoft.com/en-us/power-pages/getting-started/developer-sites)
* Content Source: [power-pages-docs/getting-started/developer-sites.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/developer-sites.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @ProfessorKendrick
* Microsoft Alias: **vamseedilli**

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  We updated the documentation (see [Creating Developer Sites](https://learn.microsoft.com/power-pages/getting-started/developer-sites#creating-developer-sites)).  Closing the issue.

**Comment by pmtate** [comment]
The page is very confusing mixing the use of "site(s)" "website(s)"
