### ISSUE TITLE
Production website

### ISSUE THREAD

**Issue by miadey** [MicrosoftDocs/power-pages-docs#55]
The list indicated that we can't & we can migrate to a production web site

-Developer websites **can't be converted to production websites.** More information: [Power Pages lifecycle](https://learn.microsoft.com/fr-fr/power-pages/admin/lifecycle)
-Each user is allowed to create three developer websites. Once you've created your developer site, you can migrate it to a test or **production site**

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6da19427-9c92-47b6-a1db-4254a67ce597
* Version Independent ID: 6da19427-9c92-47b6-a1db-4254a67ce597
* Content: [Use developer websites](https://learn.microsoft.com/fr-fr/power-pages/getting-started/developer-sites)
* Content Source: [power-pages-docs/getting-started/developer-sites.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/developer-sites.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @ProfessorKendrick
* Microsoft Alias: **vamseedilli**

**Comment by nickdoelman** [comment]
Thank you for the feedback. The process of converting a website is different than migrating a website. We are updating our documentation to explain the differences. You cannot convert a developer website to a production website but you can migrate a developer website to a production site.
