### ISSUE TITLE
Additional role reqs for creating a website

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/power-pages-docs#57]
In the "Create a website" row where "Required roles and permissions in Microsoft Power Platform" are listed, in addition to the "System Administrator" role, a user also needs the "Basic User" and "Environment Maker" roles. The UI will say you don't have permissions otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20c84550-bfea-6a51-3b10-87175c8a038b
* Version Independent ID: 20c84550-bfea-6a51-3b10-87175c8a038b
* Content: [Roles required for Power Pages administration](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles)
* Content Source: [power-pages-docs/admin/admin-roles.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/admin/admin-roles.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**[Create a website](https://learn.microsoft.com/en-us/power-pages/getting-started/create-manage)	Required roles and permissions in Microsoft Power Platform (all are required):
A user account with [Read-Write Access Mode](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles#read-write-access-mode).
[System administrator](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles#system-administrator) role.
[Permissions to register an app](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#permissions-required-for-registering-an-app) in Azure AD are required.
Is [website creation disabled](https://learn.microsoft.com/en-us/power-apps/maker/portals/control-portal-creation) in the tenant?
If Yes, in addition to the roles and permissions above, a user will also need at least one of the following roles to create a website: [Global administrator](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles#global-administrator), [Dynamics 365 administrator](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles#dynamics-365-administrator), or [Power Platform administrator](https://learn.microsoft.com/en-us/power-pages/admin/admin-roles#power-platform-administrator).

**Comment by nickdoelman** [comment]
Thank you for your feedback and sorry to hear you are having issues. In our testing, only the **system administrator** role should be required to create a website. This may be something unique to your environment, I would suggest you engage with [support](https://powerapps.microsoft.com/support/pro/) to help you isolate the issue.
