### ISSUE TITLE
Cannot find web application firewall

### ISSUE THREAD

**Issue by reggiegupta** [MicrosoftDocs/power-pages-docs#58]
[Enter feedback here]
There is no provision to view web application firewall and enable/disable it using the instructions provided in this link - that was referenced in the site health section for the power pages site. The sections shown in the screenshot are no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8122ad-5f7b-cedf-707b-7bc056ae43c6
* Version Independent ID: 4a8122ad-5f7b-cedf-707b-7bc056ae43c6
* Content: [Configure Web Application Firewall for Power Pages (preview)](https://learn.microsoft.com/en-us/power-pages/security/configure-web-application-firewall)
* Content Source: [power-pages-docs/security/configure-web-application-firewall.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/configure-web-application-firewall.md)
* Service: **power-pages**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by ProfessorKendrick** [comment]
Thank you for bringing this to our attention. We've revised the content.  Closing the issue.
