### ISSUE TITLE
add simple text inside form

### ISSUE THREAD

**Issue by mohamedafimto** [MicrosoftDocs/power-pages-docs#59]
how to add a simple label text inside the form.

**Comment by nickdoelman** [comment]
Can you provide more details or link to specific topic where you asking the question?
There is a topic here that describes editing the label text on forms:
https://learn.microsoft.com/power-pages/getting-started/add-form#edit-a-text-field-on-the-form

**Comment by ProfessorKendrick** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
