### ISSUE TITLE
Please review the recommended value of the CSP

### ISSUE THREAD

**Issue by TaehyungAlexKim** [MicrosoftDocs/power-pages-docs#60]
The recommended value of the CSP written in the last table seems a little kinder [script-src https: 'nonce'] than ['nonce']. What do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32dfe62d-84d9-fa1f-742b-91f2f0c3478c
* Version Independent ID: 32dfe62d-84d9-fa1f-742b-91f2f0c3478c
* Content: [Security issues (preview)](https://learn.microsoft.com/en-us/power-pages/security/site-checker-security?WT.mc_id=powerportals_inproduct_portalstudio2#http-headers)
* Content Source: [power-pages-docs/security/site-checker-security.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/site-checker-security.md)
* Service: **power-pages**
* GitHub Login: @vamseedillimsft
* Microsoft Alias: **vamseedilli**

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Closing the issue.
