### ISSUE TITLE
Print screens

### ISSUE THREAD

**Issue by fonsell** [MicrosoftDocs/power-pages-docs#61]
It would be valuable to have example print screens added to these documentations

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40bd80fe-8db9-a5fc-58e0-87d49689049e
* Version Independent ID: 40bd80fe-8db9-a5fc-58e0-87d49689049e
* Content: [Configure multistep form metadata for Power Pages](https://learn.microsoft.com/en-us/power-pages/configure/configure-multistep-form-metadata)
* Content Source: [power-pages-docs/configure/configure-multistep-form-metadata.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/configure-multistep-form-metadata.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by ProfessorKendrick** [comment]
Thank you for the feedback.  We'll review the topic and make necessary enhancements.  Closing the issue.
