### ISSUE TITLE
Limitations not only with Parental scope (seen also with contact or account scope)

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/power-pages-docs#62]
please change

Users will get a CDS error if they invoke a GET Web API request for tables that have multiple levels of 1 to many or many to many [table permissions](https://learn.microsoft.com/en-us/power-pages/security/table-permissions) with parent scope defined.

to

Users may get a CDS error if they invoke a GET Web API request for tables that have multiple levels of 1 to many or many to many [table permissions](https://learn.microsoft.com/en-us/power-pages/security/table-permissions) when Parental, Contact or Account scope adds extra conditions to the query

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 086e493d-26d0-83c1-55cd-62f592ede2ca
* Version Independent ID: 086e493d-26d0-83c1-55cd-62f592ede2ca
* Content: [Overview of the Power Pages portals Web API](https://learn.microsoft.com/en-us/power-pages/configure/web-api-overview#known-issues)
* Content Source: [power-pages-docs/configure/web-api-overview.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/web-api-overview.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated and the changes will be visible soon.
