### ISSUE TITLE
Token endpoint result

### ISSUE THREAD

**Issue by anantharajaraman1977** [MicrosoftDocs/power-pages-docs#63]
The documentation is inconsistent and confusing. The page mentions token endpoint, but it is not clear if it returns an ID token or Access Token. The table with input parameters for token endpoint refers to access token, but rest of the page refers to ID token.

Also, if Portal has implemented Implicit Grant, why are we using token endpoint? I'tsn a Token Endpoint typically used with Authorisation Code flow in OAuth? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17dd281e-3c90-c9cb-6428-760df55dd5e8
* Version Independent ID: 17dd281e-3c90-c9cb-6428-760df55dd5e8
* Content: [Use OAuth 2.0 implicit grant flow in your Power Pages site](https://learn.microsoft.com/en-us/power-pages/security/oauth-implicit-grant-flow)
* Content Source: [power-pages-docs/security/oauth-implicit-grant-flow.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/oauth-implicit-grant-flow.md)
* Service: **power-pages**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by ProfessorKendrick** [comment]
Thank you for contacting us.  We've updated the documentation:  https://learn.microsoft.com/en-us/power-pages/security/oauth-implicit-grant-flow

Please review and reach back out if you still have questions.  Closing this issue.
