### ISSUE TITLE
Should the API endpoint in this example be enclosed in quotes?

### ISSUE THREAD

**Issue by admouk** [MicrosoftDocs/power-pages-docs#64]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c7bdf78-94a5-558f-32df-2355593b6f48
* Version Independent ID: 0c7bdf78-94a5-558f-32df-2355593b6f48
* Content: [Configure Power Automate cloud flows in Power Pages (preview)](https://learn.microsoft.com/en-us/power-pages/configure/cloud-flow-integration)
* Content Source: [power-pages-docs/configure/cloud-flow-integration.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/cloud-flow-integration.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @nageshbhat-msft
* Microsoft Alias: **nabha**

**Comment by nickdoelman** [comment]
Thank you for your feedback. Documentation has been updated.
