### ISSUE TITLE
Multiple Step Form questions

### ISSUE THREAD

**Issue by jaimieji** [MicrosoftDocs/power-pages-docs#65]
Hi,

Are there any conditions for this to work "Add multiple entries per person" or how is it working for a anonymous form? If we want to limit one entry per person for anonymous form submission. 

What is the best way to migrate from the old multiple step form based on "one form and tabs" to the new approach of "one step per form"?

Regards
Jaimie

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d50be7b6-9a15-ad35-8b2a-debf34a6eebd
* Version Independent ID: d50be7b6-9a15-ad35-8b2a-debf34a6eebd
* Content: [Multistep forms](https://learn.microsoft.com/en-us/power-pages/getting-started/multistep-forms)
* Content Source: [power-pages-docs/getting-started/multistep-forms.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/multistep-forms.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @pranita225
* Microsoft Alias: **prpadalw**

**Comment by nickdoelman** [comment]
Thank you for your feedback.

Power Pages doesn’t have a reliable way to track if the same anonymous user has submitted a form multiple times, nor is there a feature to prevent this. Documentation updated.

You will not need to migrate the multistep form using tabs, as this can still be maintained and managed using the Portals Management app and will continue to work on Power Pages websites. To utilize the design studio, you will need to create new unique forms for each step, there is no migration process.

**Comment by jaimieji** [comment]
Hi,

Thank you. Mainly it look easier to maintain the new form based multi step form compared with the tab based one. Our customer currently is using D365 portal and in process to migrate to Power Pages. Using the tab based form will introduce more overhead for this to be maintained by customer based on their demand and the drive to move to Power Pages. 

If the process is to recreate them using form based, that is fine. Just want to know if there is a quicker way to convert from tab based to form based.
