### ISSUE TITLE
Tabs and links don't exist

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-pages-docs#66]
[Enter feedback here]
Once you sign in to https://aka.ms/mpp, there is no solution tab on the left-hand side as showed in the steps and demo video. No further steps can be performed.

https://learn.microsoft.com/en-us/power-pages/configure/power-pages-solutions?WT.mc_id=powerportals_community_productblog#add-power-pages-site-and-components-to-a-solution

https://powerpages.microsoft.com/en-us/blog/power-pages-alm-using-solutions-preview/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5f7113-9544-1bd9-aebe-2cd10ff9273b
* Version Independent ID: 6c5f7113-9544-1bd9-aebe-2cd10ff9273b
* Content: [Use solutions with Power Pages](https://learn.microsoft.com/en-us/power-pages/configure/power-pages-solutions?WT.mc_id=powerportals_community_productblog)
* Content Source: [power-pages-docs/configure/power-pages-solutions.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/power-pages-solutions.md)
* Service: **power-pages**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback and sorry you are having issues. The side tab with the solution option appears for all the environments I have tested. 

This seems like it may be an issue on your specific environment, I would suggest opening a support ticket.

To contact Support, see here: https://powerpages.microsoft.com/support/

**Comment by ahmadpirani** [comment]
Well, explicitly going to
https://make.powerpages.microsoft.com/environments/<GUID>/portals/home is
the only way it works. Logging into https://make.powerpages.microsoft.com/
always goes to the page below.

I am not going to contact Microsoft support as they are, in my and other
colleagues' experiences, very delayed and  vague in responses. Asking to
perform the exact same steps that we send most of the time along with
support tickets.

Thanks for your responses.


[image: image.png]

**Comment by nickdoelman** [comment]
For some reason the image didn't come through, I have re-opened the issue, hopefully that will help.

Is it this screen that you are seeing? (if not, please try posting it again)
![image](https://github.com/MicrosoftDocs/power-pages-docs/assets/91484437/c3f34e7e-21e2-4360-98a7-4731f6551430)

**Comment by ahmadpirani** [comment]
Yes, this is the page it takes to after signing in. I have to explicitly
change the URL to a specific environment. Selecting the environment from
the top right hand corner does nothing. Thank you very much for your
continued help.

**Comment by nickdoelman** [comment]
OK, this is known as the "first run experience" meaning it should only appear the first time a user goes to the Power Pages website, the process will create a developer environment and developer website. After that developer environment and first site is created, it shouldn't appear again for that user. Using the link you specified is the workaround to avoid this. I will provide this feedback to the team.

**Comment by ahmadpirani** [comment]
I see what you mean. But they should at least not show this landing page where there exists one or more sites.
-------- Original message --------From: nickdoelman ***@***.***> Date: 9/6/23  10:53  (GMT-08:00) To: MicrosoftDocs/power-pages-docs ***@***.***> Cc: Ahmad Pirani ***@***.***>, Author ***@***.***> Subject: Re: [MicrosoftDocs/power-pages-docs] Tabs and links don't exist
  (Issue #66) 
OK, this is known as the "first run experience" meaning it should only appear the first time a user goes to the Power Pages website, the process will create a developer environment and developer website. After that developer environment and first site is created, it shouldn't appear again for that user. Using the link you specified is the workaround to avoid this. I will provide this feedback to the team.
