### ISSUE TITLE
Azure AD B2C as Identity Provider

### ISSUE THREAD

**Issue by randolphnz** [MicrosoftDocs/power-pages-docs#68]
Hi Team,

The power page website can be used externally only with Azure AD B2C as the only identity provider.

In this scenario, could I have a diagram how Power Pages site connects to Dataverse?

Regards,
Randy
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69de5a40-2d5f-090c-677b-88c6240e3901
* Version Independent ID: 69de5a40-2d5f-090c-677b-88c6240e3901
* Content: [Power Pages connectivity to a Microsoft Dataverse](https://learn.microsoft.com/en-us/power-pages/admin/connectivity)
* Content Source: [power-pages-docs/admin/connectivity.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/admin/connectivity.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by nickdoelman** [comment]
Please check out this topic: [Power Pages connectivity to a Microsoft Dataverse](https://learn.microsoft.com/power-pages/admin/connectivity).
