### ISSUE TITLE
Update steps

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-pages-docs#69]
[Enter feedback here]
https://learn.microsoft.com/en-us/power-pages/admin/update-solution#method-2-update-website-packages-by-using-the-site-list-for-a-tenant

Steps needs to be updated. Clicking on the site opens the details of that site but there is no 'Check portal package(s) for upgrade' option there anymore. It is not in the previous page itself. Click on the ellipsis next to the site name that you want to check updated portal packages for on "https://admin.powerplatform.microsoft.com/resources/portals" page. Then select 'Check portal package(s) for upgrade'.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3689bb4-869c-c5fc-dc27-0a8746732f4a
* Version Independent ID: b3689bb4-869c-c5fc-dc27-0a8746732f4a
* Content: [Update the Power Pages solution](https://learn.microsoft.com/en-us/power-pages/admin/update-solution)
* Content Source: [power-pages-docs/admin/update-solution.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/admin/update-solution.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for your feedback. The option still appears, but the interface has changed slightly, and the screen shot in the documentation has been updated.

**Comment by ahmadpirani** [comment]
Thanks, Nick! As always, very helpful.
