### ISSUE TITLE
Edit multilingual content in Design Studio

### ISSUE THREAD

**Issue by julienbiedermann** [MicrosoftDocs/power-pages-docs#7]
Hello,

I din't find any information about editing multilingual content directly in Design Studio. Do you know if it is possible or is it planned in a next release wave ?

Thanks a lot

Best Regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd1052-c2bb-3647-7534-94e43ca62bd5
* Version Independent ID: 6edd1052-c2bb-3647-7534-94e43ca62bd5
* Content: [Use design studio](https://learn.microsoft.com/en-us/power-pages/getting-started/use-design-studio)
* Content Source: [power-pages-docs/getting-started/use-design-studio.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/use-design-studio.md)
* Service: **power-pages**
* GitHub Login: @clromano
* Microsoft Alias: **clromano**

**Comment by ProfessorKendrick** [comment]
Thank you for your inquiry.  

Currently, multilingual content cannot be edited directly in Design studio and would need to be done in the Portals Management App.

Here is a link to the release plan so you can stay up-to-date on upcoming features:
https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave1/power-pages/planned-features

Closing this issue.
