### ISSUE TITLE
"Configure Child Permissions"

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/power-pages-docs#73]
The section
https://learn.microsoft.com/en-us/power-pages/security/table-permissions#configure-child-permissions
currently only documents how you can create a record (which is fairly obvious and would not really need specific documentation)

What is completely missing is documentation on
- how exactly child permissions work and how they are supposed to be used
- what effect the Parental scope on child permissions has (and how to even see this when the scope of the child permission is not even displayed on the grid showing added child permissions)
- how to see all privileges a web role has (including child permissions) without stepping through all individual table permissions and their children

- EXAMPLES of a sensible child permission setup, e.g.
having Contact scope on Project (custom field on case)
and then adding child permissions for cases with parental scope
to give the web role access to all cases when the portal user has access to the project

Without examples, the name "child" permission without further explanations may be misleading 
when it gives access to the main record (case) via one of its less relevant looking fields (project)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5dd7334-1124-4cb2-322a-79a6735d5852
* Version Independent ID: e5dd7334-1124-4cb2-322a-79a6735d5852
* Content: [Set table permissions in Power Pages](https://learn.microsoft.com/en-us/power-pages/security/table-permissions#configure-child-permissions)
* Content Source: [power-pages-docs/security/table-permissions.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/table-permissions.md)
* Service: **power-pages**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Closing this issue.
