### ISSUE TITLE
Public federation endpoint with publicly-trusted SSL certificate

### ISSUE THREAD

**Issue by amasse3** [MicrosoftDocs/power-pages-docs#77]
We should include in the FAQ so customers understand their SAML 2.0 Identity Provider endpoints and metadata must be publicly accessible and using a publicly trusted SSL certificate. I support customers that like to keep their federation service private and use SSL certificates from their internal PKI. Doing this results in 500 error at sign-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78e335b4-325c-7971-a8ed-24694a143ced
* Version Independent ID: 78e335b4-325c-7971-a8ed-24694a143ced
* Content: [FAQs about using SAML 2.0 in Power Pages](https://learn.microsoft.com/en-us/power-pages/security/authentication/saml2-faqs)
* Content Source: [power-pages-docs/security/authentication/saml2-faqs.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/authentication/saml2-faqs.md)
* Service: **power-pages**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by ProfessorKendrick** [comment]
Thanks for your feedback. We've added a note to the documentation: [Set up a SAML 2.0 provider](https://learn.microsoft.com/en-us/power-pages/security/authentication/saml2-provider#enter-site-settings-in-power-pages). Closing the issue.
