### ISSUE TITLE
Advanced Forms name not used

### ISSUE THREAD

**Issue by sam-programming** [MicrosoftDocs/power-pages-docs#8]
Not called Advanced Forms in the Portal Management Page, they are called Multistep Forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4343925c-3249-ca9d-fc71-0d2f79ba2739
* Version Independent ID: 4343925c-3249-ca9d-fc71-0d2f79ba2739
* Content: [Tutorial: Add a multi-step form to your page](https://learn.microsoft.com/en-us/power-pages/getting-started/tutorial-add-multi-step-form)
* Content Source: [power-pages-docs/getting-started/tutorial-add-multi-step-form.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/getting-started/tutorial-add-multi-step-form.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @nickdoelman
* Microsoft Alias: **ndoelman**

**Comment by nickdoelman** [comment]
This topic has been updated.
