### ISSUE TITLE
Had great difficulty finding "setup"

### ISSUE THREAD

**Issue by jennabourgeois** [MicrosoftDocs/power-pages-docs#82]
[Enter feedback here]
This page needs to be more descriptive.  It took me forever to find the "setup" as described.  I found it by creating a power pages website, clicking on "edit" to edit the site.  Perhaps you can add a note about this.  

Jenna Bourgeois

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4787dbfc-2e6a-609e-818d-b2de4c247f4d
* Version Independent ID: 4787dbfc-2e6a-609e-818d-b2de4c247f4d
* Content: [Set up site authentication](https://learn.microsoft.com/en-us/power-pages/security/authentication/configure-site#select-general-authentication-settings)
* Content Source: [power-pages-docs/security/authentication/configure-site.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/authentication/configure-site.md)
* Service: **power-pages**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Closing this issue.
