### ISSUE TITLE
Is there planned obsolescence for Portal Management?

### ISSUE THREAD

**Issue by degrover-cn** [MicrosoftDocs/power-pages-docs#85]
With the advent of “Power Pages Management”, discussed here, it would be nice to know how long we can expect LTS for Portal Management. We are considering automating portal form generation for a large number of forms and the "standard data model" used by Portal Management being entirely within Dataverse entities makes that a more appealing target for automation than the "enhanced" model with more complex configuration storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd181e9b-633b-0d4b-da02-b15c5787a8ae
* Version Independent ID: fd181e9b-633b-0d4b-da02-b15c5787a8ae
* Content: [Portal Management app overview](https://learn.microsoft.com/en-us/power-pages/configure/portal-management-app)
* Content Source: [power-pages-docs/configure/portal-management-app.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/portal-management-app.md)
* Service: **power-pages**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by ProfessorKendrick** [comment]
Thank you for reaching out.  I've received the following information to share with you:

The Portal Management application will continue exist to support standard data model application; however, we recommend using [enhance data model](https://learn.microsoft.com/power-pages/admin/enhanced-data-model) for new sites as we plan to deprecate standard data model and the same will be applicable to Portal Management application.  

Closing the issue.
