### ISSUE TITLE
Is this production ready? MS support suggests to turn this feature on for WAF.

### ISSUE THREAD

**Issue by crsnt** [MicrosoftDocs/power-pages-docs#86]
Hello, 

Can someone please confirm if this feature can be used in production? Talking to MS support they told us:
- [https://learn.microsoft.com/en-us/power-pages/configure/azure-front-door](https://learn.microsoft.com/en-us/power-pages/configure/azure-front-door ) documentation is outdated. (as we hit some error following step 2b - **Another custom domain with the same host name already exists.**

- We should just follow [https://learn.microsoft.com/en-us/power-pages/admin/add-custom-domain](https://learn.microsoft.com/en-us/power-pages/admin/add-custom-domain) and turn on WAF feature (which I believe still in Preview)

They cannot confirm whether this feature is production ready. Can you please advise?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8122ad-5f7b-cedf-707b-7bc056ae43c6
* Version Independent ID: 4a8122ad-5f7b-cedf-707b-7bc056ae43c6
* Content: [Configure Web Application Firewall for Power Pages (preview)](https://learn.microsoft.com/en-us/power-pages/security/configure-web-application-firewall)
* Content Source: [power-pages-docs/security/configure-web-application-firewall.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/configure-web-application-firewall.md)
* Service: **power-pages**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by ProfessorKendrick** [comment]
You can enable platform provided WAF feature in production. If you want granular control on WAF rules, you can directly use Azure front door. If you are using your own Azure front door (bring your own WAF) option, you shouldn't enable OOB CDN/WAF capabilities. Closing this issue.
