### ISSUE TITLE
Some missing info for template usage

### ISSUE THREAD

**Issue by NL12143** [MicrosoftDocs/power-pages-docs#89]
Please add some valid input values for the templates. 
For example a valid zip code for the "book-a-meeting" template, e.g. "98109"
And correct reference to tables. It uses Location (msdyn_location)
And that admin is under ../home_admin/ 

For registration ../admin-home/ to get into adminstration (registrations). 

Maybe some information on using bas64 for an image .. takes long loading.
It is maybe a limitation by dataverse ?

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Closing this issue.

**Comment by ProfessorKendrick** [comment]
I've passed your feedback on to the product team for review.

**Comment by NL12143** [comment]
Kudos!
