### ISSUE TITLE
Info on how the builtin provider "AzureAD" is build

### ISSUE THREAD

**Issue by NL12143** [MicrosoftDocs/power-pages-docs#90]
Please add some documentation on how the identity provider Azure AD is set.  
Since it is not possible to open its configuration settings :-(  just to read it, not edit. 
 
The button says "Azure AD". Most users simply do not understand that. 
Please change the built in provider to use as a label "Microsoft 365". 
No please do't change it to "Entra ID" in respect of our poor users.

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Closing this issue.

**Comment by NL12143** [comment]
How this was solved ? 
I still have end-users that do not know what sign-in with "Azure-AD" means. And I get that ... 

I understand it is not a documentation issue but one needs to start somewhere ...

**Comment by ProfessorKendrick** [comment]
I've passed your feedback on to the product team for review.  Documentation on identity providers is available here:  https://learn.microsoft.com/en-us/power-pages/security/authentication/#common-identity-providers
