### ISSUE TITLE
Add Instructions for comparing lookup fields

### ISSUE THREAD

**Issue by JMonks14** [MicrosoftDocs/power-pages-docs#94]
When using a condition step to check the value of a lookup field you have to use the capitalised guid of the lookup value for caparison. nowhere in the documentation is it mentioned that it needs to be capitalised and it is not obvious. this should be added to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84973ba5-4c5f-1c67-3f99-fc5e9bd3e11d
* Version Independent ID: 84973ba5-4c5f-1c67-3f99-fc5e9bd3e11d
* Content: [Add a conditional step type](https://learn.microsoft.com/en-us/power-pages/configure/add-conditional-step)
* Content Source: [power-pages-docs/configure/add-conditional-step.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/add-conditional-step.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  Closing the issue.
