### ISSUE TITLE
Power Pages Flow will return 502 IncorrectPayload error If I return 500 response in Flow Action

### ISSUE THREAD

**Issue by wuxiaojun514** [MicrosoftDocs/power-pages-docs#97]
### How to reproduce
I created a power pages flow as guideline.
It works well until I added a condition to return 500 response 
![image](https://github.com/MicrosoftDocs/power-pages-docs/assets/29603048/108df827-5054-4636-8a02-5737c6baef94)
Then I got "IncorrectPayload" error in the front-end.
![image](https://github.com/MicrosoftDocs/power-pages-docs/assets/29603048/9fd0ddc2-36e2-4a21-b747-e144d5d870d8)

### Expected behavior
It should return the error message I set in the response action, not this "IncorrectPayload" error.
By the way, if you call power pages flow without adding "eventData" object outside the real parameter, you will also get  "IncorrectPayload" error

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c7bdf78-94a5-558f-32df-2355593b6f48
* Version Independent ID: 0c7bdf78-94a5-558f-32df-2355593b6f48
* Content: [Configure Power Automate cloud flows in Power Pages](https://learn.microsoft.com/en-us/power-pages/configure/cloud-flow-integration)
* Content Source: [power-pages-docs/configure/cloud-flow-integration.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/configure/cloud-flow-integration.md)
* Service: **power-pages**
* Sub-service: ****
* GitHub Login: @nageshbhat-msft
* Microsoft Alias: **nabha**

**Comment by ProfessorKendrick** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: [https://powerpages.microsoft.com/en-us/support/](https://admin.powerplatform.microsoft.com/support%22%20HYPERLINK%20%22https://powerpages.microsoft.com/en-us/support/) 

Closing this issue.
